# Assign PR to Author
# Scan your repo for secrets. AWS tokens, keys, etc.
# https://github.com/samspills/assign-pr-to-author

name: AutoAssigner
on: [pull_request]

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
    - uses: samspills/assign-pr-to-author@v1.0
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN }}'
