# Secret Scan
# Scan your repo for secrets. AWS tokens, keys, etc.
# https://github.com/max/secret-scan

name: Secret Scan
on: [push]

jobs:
  scanSecrets:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: max/secret-scan@master
